{{- if not .Values.odootools.externalSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odootools.fullname" . }}
  labels:
    {{- include "odootools.labels" . | nindent 4 }}
stringData:
  {{- range $key, $value := .Values.odootools.secretEnvs }}
    {{ $key }}: {{ $value }}
  {{- end }}
{{- end -}}
