ingress:
  enabled: true
  hosts:
    - host: odootools.vshn.net
      paths:
        - path: /
          pathType: Exact
  tls:
    - secretName: odootools-tls
      hosts:
        - odootools.vshn.net
