ingress:
  enabled: true
  hosts:
    - host: odootools.vshn.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: odootools-tls
      hosts:
        - odootools.vshn.net
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
